package main

import (
	"github.com/gin-gonic/gin"
)

func (application *application) router() *gin.Engine {
	router := gin.Default()
	networkAdmission := newNetworkAdmissionController(loadNetworkAdmissionPolicy())
	router.Use(securityHeadersMiddleware(), networkAdmissionMiddleware(networkAdmission), corsMiddleware(), requestIDMiddleware(), endpointProtectionMiddleware(), auditLogMiddleware())

	router.GET("/health", handleHealth)
	router.GET("/api/system/network-admission", handleNetworkAdmission(networkAdmission))
	router.PUT("/api/system/network-admission", handleUpdateNetworkAdmission(networkAdmission))
	router.GET("/api/system/runtime-identity", handleRuntimeIdentity)
	router.GET("/api/scan/ws", application.handleScanProgressWebSocket)
	router.POST("/api/scan", application.handleScan)
	router.POST("/api/scan/:id/cancel", application.handleCancelScan)
	router.POST("/api/compare", application.handleCompare)
	router.POST("/api/export", application.handleExport)
	router.POST("/api/export/download", application.handleExportDownload)
	router.POST("/api/export/summary", application.handleExportSummary)
	router.GET("/api/export/summary/templates", application.handleListExportSummaryTemplates)
	router.POST("/api/ad/discover", application.handleADDiscover)
	router.GET("/api/ad/connections", application.handleListADConnections)
	router.POST("/api/ad/connections", application.handleCreateADConnection)
	router.PUT("/api/ad/connections/:id", application.handleUpdateADConnection)
	router.DELETE("/api/ad/connections/:id", application.handleDeleteADConnection)
	router.POST("/api/ad/connections/:id/test", application.handleTestADConnection)
	router.POST("/api/ad/test", application.handleADTest)
	router.POST("/api/ad/users/query", application.handleADUserQuery)
	router.POST("/api/ad/users/query/async", application.handleADUserQueryAsync)
	router.POST("/api/ad/groups/query", application.handleADGroupQuery)
	router.POST("/api/ad/groups/members", application.handleADGroupMembers)
	router.POST("/api/ad/principals/expand", application.handleADPrincipalExpand)
	router.POST("/api/ad/tree", application.handleADTree)
	router.POST("/api/ad/tree/explain", application.handleADTreeExplain)
	router.POST("/api/ad/sync", application.handleStartDirectorySync)
	router.GET("/api/ad/sync/runs", application.handleListDirectorySyncRuns)
	router.GET("/api/ad/sync/runs/:id", application.handleGetDirectorySyncRun)
	router.POST("/api/access/by-user", application.handleAccessByUser)
	router.POST("/api/access/by-resource", application.handleAccessByResource)
	router.GET("/api/ad/jobs", application.handleListADJobs)
	router.GET("/api/ad/jobs/:id", application.handleGetADJob)
	router.POST("/api/ad/jobs/:id/cancel", application.handleCancelADJob)
	router.POST("/api/ad/jobs/:id/retry", application.handleRetryADJob)
	router.POST("/api/permissions/conflicts", application.handlePermissionConflicts)
	router.GET("/api/file-activity/readiness", application.handleFileActivityReadiness)
	router.GET("/api/file-activity/events", application.handleListFileActivityEvents)
	router.POST("/api/file-activity/events/query", application.handleQueryFileActivityEvents)
	router.GET("/api/audit/requests", application.handleListAuditRequests)
	router.POST("/api/audit/requests/export/summary", application.handleExportAuditSummary)
	router.GET("/api/audit/requests/:request_id", application.handleGetAuditRequest)
	router.GET("/api/fs/directories", application.handleListDirectories)
	router.GET("/api/sessions", application.handleListSessions)
	router.GET("/api/sessions/:id", application.handleGetSession)
	router.GET("/api/sessions/:id/bundle", application.handleGetSessionBundle)
	router.GET("/api/sessions/:id/permissions", application.handleListSessionPermissions)
	router.GET("/api/sessions/:id/folders", application.handleListSessionFolders)
	router.GET("/api/sessions/:id/changes", application.handleListSessionChanges)

	return router
}
