version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /apps/backend
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: /apps/desktop-win
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
